package com.raggamuffin.protorunnerv2.pubsub;

public enum PublishedTopics 
{
	SwitchScreen,
	StartGame,
    StartTutorial,
    NextTutorialButtonPressed,
    TutorialComplete,
    LeaderboardPressed,
    AchievementsPressed,
	EndGame,
	PlayerSpawned,
	PlayerHit,
	PlayerShotFired,
	EnemyHit,
	EnemyDestroyed,
	WingmanDestroyed,
	PlayerDestroyed,
	PlayerSwitchedWeapon,
    SignInPressed,
    SignOutPressed,
    GooglePlayConnected,
    GooglePlayDisconnected,

    // Controls
    EvadeLeft,
    EvadeRight,
    StrafeLeft,
    StrafeRight,
    AfterBurnersEngage,
    AfterBurnersDisengage,
    Reverse,
    Forward,
    Fire,
    CeaseFire,
    WeaponLeft,
    WeaponRight,
    WeaponUp,
    WeaponDown,
}